[package]
name = "gossamer-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Language-server-protocol adapter for Gossamer."

[lints]
workspace = true

[dependencies]
gossamer-ast = { workspace = true }
gossamer-diagnostics = { workspace = true }
gossamer-hir = { workspace = true }
gossamer-interp = { workspace = true }
gossamer-lex = { workspace = true }
gossamer-lint = { workspace = true }
gossamer-parse = { workspace = true }
gossamer-pkg = { workspace = true }
gossamer-resolve = { workspace = true }
gossamer-runtime = { workspace = true }
gossamer-std = { workspace = true }
gossamer-types = { workspace = true }
unicode-ident = { workspace = true }

[dev-dependencies]
gossamer-driver = { workspace = true }
