[package]
name = "gossamer-codegen-llvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "LLVM-backed codegen for the Gossamer compiler."

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
gossamer-abi = { workspace = true }
gossamer-lex = { workspace = true }
gossamer-mir = { workspace = true }
gossamer-resolve = { workspace = true }
gossamer-types = { workspace = true }
parking_lot = { workspace = true }
sha2 = { workspace = true }
wait-timeout = { workspace = true }

[dev-dependencies]
gossamer-parse = { workspace = true }
gossamer-hir = { workspace = true }
gossamer-types = { workspace = true }
insta = { workspace = true }
