//! C-ABI dispatch shims for `std::crypto::aead` (AES-256-GCM,
//! ChaCha20-Poly1305) and `std::crypto::ed25519`. These mirror the
//! bytecode-VM builtins in
//! `gossamer-interp/src/stdlib_builtins/crypto_breadth.rs` so the
//! compiled (Cranelift / LLVM) tier resolves the same calls natively
//! instead of failing to link.
//!
//! Shapes match the interp's value model and `gossamer-std`'s
//! `crypto.rs` construction so a value produced on one tier matches
//! another bit-for-bit:
//! - `aead::*_seal` / `*_open` take four `[u8]` byte vectors
//!   (`key`, `nonce`, `data`, `aad`) and return
//!   `Result<Vec<u8>, errors::Error>` packed as the runtime's `i128`.
//! - `ed25519::keypair()` returns
//!   `Result<(Vec<u8>, Vec<u8>), errors::Error>` - the Ok payload is a
//!   16-byte heap pair `(secret_ptr, public_ptr)` of `*mut GosVec`,
//!   matching the bytecode VM's `Value::Tuple([secret, public])`.
//! - `ed25519::sign(secret, msg)` returns
//!   `Result<Vec<u8>, errors::Error>` (64-byte signature).
//! - `ed25519::verify(public, msg, sig)` returns
//!   `Result<(), errors::Error>` - `Ok(())` packed as disc `0`,
//!   payload `0` (mirrors the VM's `ok_variant(Value::Unit)`).
//!
//! AEAD construction (`Aes256Gcm` / `ChaCha20Poly1305` via the
//! `aead::{Aead, KeyInit, Payload}` traits, 32-byte key / 12-byte
//! nonce, ciphertext-with-tag output) is copied verbatim from
//! `gossamer-std/src/crypto.rs`. Ed25519 keys are generated by seeding
//! `SigningKey::from_bytes` with 32 OS-CSPRNG bytes (equivalent to
//! `SigningKey::generate`, which fills the same 32-byte secret); sign /
//! verify use the standard `ed25519_dalek` `Signer` / `Verifier`
//! surface, identical to the std impl.

#![allow(clippy::missing_safety_doc)]
#![allow(missing_docs)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_sign_loss)]

use super::encoding::{bytes_to_gosvec, gosvec_u8};
use super::vec::GosVec;

/// AES-256-GCM / ChaCha20-Poly1305 key length in bytes.
const KEY_LEN: usize = 32;
/// AEAD nonce length in bytes (96-bit, shared by both algorithms).
const NONCE_LEN: usize = 12;

/// Packs an `Err(errors::Error)` for the Result-returning AEAD /
/// ed25519 shims (disc `1`, payload = a fresh `errors::Error`).
fn aead_err(msg: &str) -> i128 {
    let err = crate::c_abi::errors::error_new_from_bytes(msg.as_bytes());
    super::vec::gos_rt_result_new(1, err as i64)
}

/// Layout of the ed25519 `([u8], [u8])` keypair: both byte vectors are owned by
/// the blob.
static KEYPAIR_VECS_META: [i64; 6] = [
    gossamer_abi::rc::RC_KIND_STRUCT,
    1,
    0,
    2,
    gossamer_abi::rc::RC_CHILD_VEC << gossamer_abi::rc::RC_CHILD_KIND_SHIFT,
    (gossamer_abi::rc::RC_CHILD_VEC << gossamer_abi::rc::RC_CHILD_KIND_SHIFT) | 1,
];

/// `crypto::aead::aes_256_gcm_seal(key, nonce, plaintext, aad)
/// -> Result<[u8], errors::Error>` - AES-256-GCM seal (ciphertext
/// followed by the 16-byte auth tag).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_aes256gcm_seal(
    key: *const GosVec,
    nonce: *const GosVec,
    plaintext: *const GosVec,
    aad: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use aes_gcm::aead::{Aead, KeyInit, Payload};
        use aes_gcm::{Aes256Gcm, Nonce as AesNonce};
        let key = unsafe { gosvec_u8(key) };
        let nonce = unsafe { gosvec_u8(nonce) };
        let pt = unsafe { gosvec_u8(plaintext) };
        let aad = unsafe { gosvec_u8(aad) };
        if key.len() != KEY_LEN {
            return aead_err(&format!("aes-256-gcm: key must be {KEY_LEN} bytes"));
        }
        if nonce.len() != NONCE_LEN {
            return aead_err(&format!("aes-256-gcm: nonce must be {NONCE_LEN} bytes"));
        }
        let cipher = match Aes256Gcm::new_from_slice(&key) {
            Ok(c) => c,
            Err(e) => return aead_err(&format!("aes-256-gcm: key: {e}")),
        };
        match cipher.encrypt(
            AesNonce::from_slice(&nonce),
            Payload {
                msg: &pt,
                aad: &aad,
            },
        ) {
            Ok(ct) => super::vec::gos_rt_result_new(0, bytes_to_gosvec(&ct) as i64),
            Err(e) => aead_err(&format!("aes-256-gcm: seal: {e}")),
        }
    })
}

/// `crypto::aead::aes_256_gcm_open(key, nonce, ciphertext, aad)
/// -> Result<[u8], errors::Error>` - AES-256-GCM open (decrypt +
/// verify). `Err` on auth-tag mismatch (e.g. wrong key).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_aes256gcm_open(
    key: *const GosVec,
    nonce: *const GosVec,
    ciphertext: *const GosVec,
    aad: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use aes_gcm::aead::{Aead, KeyInit, Payload};
        use aes_gcm::{Aes256Gcm, Nonce as AesNonce};
        let key = unsafe { gosvec_u8(key) };
        let nonce = unsafe { gosvec_u8(nonce) };
        let ct = unsafe { gosvec_u8(ciphertext) };
        let aad = unsafe { gosvec_u8(aad) };
        if key.len() != KEY_LEN {
            return aead_err(&format!("aes-256-gcm: key must be {KEY_LEN} bytes"));
        }
        if nonce.len() != NONCE_LEN {
            return aead_err(&format!("aes-256-gcm: nonce must be {NONCE_LEN} bytes"));
        }
        let cipher = match Aes256Gcm::new_from_slice(&key) {
            Ok(c) => c,
            Err(e) => return aead_err(&format!("aes-256-gcm: key: {e}")),
        };
        match cipher.decrypt(
            AesNonce::from_slice(&nonce),
            Payload {
                msg: &ct,
                aad: &aad,
            },
        ) {
            Ok(pt) => super::vec::gos_rt_result_new(0, bytes_to_gosvec(&pt) as i64),
            Err(e) => aead_err(&format!("aes-256-gcm: open: {e}")),
        }
    })
}

/// `crypto::aead::chacha20_poly1305_seal(key, nonce, plaintext, aad)
/// -> Result<[u8], errors::Error>` - ChaCha20-Poly1305 seal.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_chacha20poly1305_seal(
    key: *const GosVec,
    nonce: *const GosVec,
    plaintext: *const GosVec,
    aad: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use aes_gcm::aead::{Aead, KeyInit, Payload};
        use chacha20poly1305::{ChaCha20Poly1305, Nonce as ChaNonce};
        let key = unsafe { gosvec_u8(key) };
        let nonce = unsafe { gosvec_u8(nonce) };
        let pt = unsafe { gosvec_u8(plaintext) };
        let aad = unsafe { gosvec_u8(aad) };
        if key.len() != KEY_LEN {
            return aead_err(&format!("chacha20-poly1305: key must be {KEY_LEN} bytes"));
        }
        if nonce.len() != NONCE_LEN {
            return aead_err(&format!(
                "chacha20-poly1305: nonce must be {NONCE_LEN} bytes"
            ));
        }
        let cipher = match ChaCha20Poly1305::new_from_slice(&key) {
            Ok(c) => c,
            Err(e) => return aead_err(&format!("chacha20-poly1305: key: {e}")),
        };
        match cipher.encrypt(
            ChaNonce::from_slice(&nonce),
            Payload {
                msg: &pt,
                aad: &aad,
            },
        ) {
            Ok(ct) => super::vec::gos_rt_result_new(0, bytes_to_gosvec(&ct) as i64),
            Err(e) => aead_err(&format!("chacha20-poly1305: seal: {e}")),
        }
    })
}

/// `crypto::aead::chacha20_poly1305_open(key, nonce, ciphertext, aad)
/// -> Result<[u8], errors::Error>` - ChaCha20-Poly1305 open.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_chacha20poly1305_open(
    key: *const GosVec,
    nonce: *const GosVec,
    ciphertext: *const GosVec,
    aad: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use aes_gcm::aead::{Aead, KeyInit, Payload};
        use chacha20poly1305::{ChaCha20Poly1305, Nonce as ChaNonce};
        let key = unsafe { gosvec_u8(key) };
        let nonce = unsafe { gosvec_u8(nonce) };
        let ct = unsafe { gosvec_u8(ciphertext) };
        let aad = unsafe { gosvec_u8(aad) };
        if key.len() != KEY_LEN {
            return aead_err(&format!("chacha20-poly1305: key must be {KEY_LEN} bytes"));
        }
        if nonce.len() != NONCE_LEN {
            return aead_err(&format!(
                "chacha20-poly1305: nonce must be {NONCE_LEN} bytes"
            ));
        }
        let cipher = match ChaCha20Poly1305::new_from_slice(&key) {
            Ok(c) => c,
            Err(e) => return aead_err(&format!("chacha20-poly1305: key: {e}")),
        };
        match cipher.decrypt(
            ChaNonce::from_slice(&nonce),
            Payload {
                msg: &ct,
                aad: &aad,
            },
        ) {
            Ok(pt) => super::vec::gos_rt_result_new(0, bytes_to_gosvec(&pt) as i64),
            Err(e) => aead_err(&format!("chacha20-poly1305: open: {e}")),
        }
    })
}

/// `crypto::ed25519::keypair() -> Result<([u8], [u8]), errors::Error>`
/// - fresh Ed25519 keypair `(secret, public)` from the OS CSPRNG.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_ed25519_keypair() -> i128 {
    ffi_entry!(0i128, {
        use ed25519_dalek::SigningKey;
        let mut seed = [0u8; 32];
        if getrandom::fill(&mut seed).is_err() {
            return aead_err("ed25519: rng failure");
        }
        let signing = SigningKey::from_bytes(&seed);
        let public = signing.verifying_key();
        let secret_vec = bytes_to_gosvec(&signing.to_bytes()) as i64;
        let public_vec = bytes_to_gosvec(&public.to_bytes()) as i64;
        let pair = crate::c_abi::rc::counted_words(&[secret_vec, public_vec], &KEYPAIR_VECS_META);
        super::vec::gos_rt_result_new(0, pair as i64)
    })
}

/// `crypto::ed25519::sign(secret, message)
/// -> Result<[u8], errors::Error>` - 64-byte detached signature.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_ed25519_sign(
    secret: *const GosVec,
    message: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use ed25519_dalek::{Signer, SigningKey};
        let secret = unsafe { gosvec_u8(secret) };
        let msg = unsafe { gosvec_u8(message) };
        let secret: [u8; 32] = match secret.as_slice().try_into() {
            Ok(s) => s,
            Err(_) => return aead_err("ed25519: secret must be 32 bytes"),
        };
        let signing = SigningKey::from_bytes(&secret);
        let sig = signing.sign(&msg).to_bytes();
        super::vec::gos_rt_result_new(0, bytes_to_gosvec(&sig) as i64)
    })
}

/// `crypto::ed25519::verify(public, message, signature)
/// -> Result<(), errors::Error>` - `Ok(())` on a valid signature,
/// `Err` otherwise. Matches the VM's `ok_variant(Value::Unit)`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn gos_rt_crypto_ed25519_verify(
    public: *const GosVec,
    message: *const GosVec,
    signature: *const GosVec,
) -> i128 {
    ffi_entry!(0i128, {
        use ed25519_dalek::{Signature, Verifier, VerifyingKey};
        let public = unsafe { gosvec_u8(public) };
        let msg = unsafe { gosvec_u8(message) };
        let sig = unsafe { gosvec_u8(signature) };
        let public: [u8; 32] = match public.as_slice().try_into() {
            Ok(p) => p,
            Err(_) => return aead_err("ed25519: public key must be 32 bytes"),
        };
        let sig: [u8; 64] = match sig.as_slice().try_into() {
            Ok(s) => s,
            Err(_) => return aead_err("ed25519: signature must be 64 bytes"),
        };
        let key = match VerifyingKey::from_bytes(&public) {
            Ok(k) => k,
            Err(e) => return aead_err(&format!("ed25519: public key: {e}")),
        };
        match key.verify(&msg, &Signature::from_bytes(&sig)) {
            Ok(()) => super::vec::gos_rt_result_new(0, 0),
            Err(e) => aead_err(&format!("ed25519: verify: {e}")),
        }
    })
}
