//! Credential store for `gos publish` / `gos yank`.
//!
//! Tokens live in `~/.gossamer/credentials.toml`, mode 600. The
//! schema is a simple `[registries."<URL>"]` table per server with
//! a single `token = "…"` field.
//!
//! `gos login --registry URL` writes a token (interactively or from
//! `$GOS_TOKEN`); `gos logout --registry URL` removes it. Every
//! authenticated registry request sends `Authorization: Bearer <token>`.

// `deny`, not `forbid`: this module is safe everywhere except the
// audited Windows-only DACL helper below, which must call Win32 FFI.
// `forbid` cannot be relaxed by a narrower `#[allow]`, so it would
// break the Windows build outright; `deny` keeps unsafe rejected by
// default while letting that one gated function opt in.
#![deny(unsafe_code)]

use std::collections::BTreeMap;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use thiserror::Error;

static CREDENTIAL_WRITE_ID: AtomicU64 = AtomicU64::new(0);

/// Errors raised by the credential store.
#[derive(Debug, Error)]
pub enum CredentialStoreError {
    /// I/O error reading or writing the credential file.
    #[error("io: {0}")]
    Io(String),
    /// File is present but contained no parseable entries.
    #[error("malformed credentials: {0}")]
    Malformed(String),
    /// `HOME` was unset and no explicit path was provided.
    #[error("HOME not set; cannot locate credential store")]
    NoHome,
}

/// Single credential entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Credential {
    /// Bearer token sent in the `Authorization` header.
    pub token: String,
}

/// File-backed credential store keyed by registry URL.
#[derive(Debug, Clone, Default)]
pub struct CredentialStore {
    /// Per-registry credential entries.
    pub entries: BTreeMap<String, Credential>,
}

impl CredentialStore {
    /// Returns an empty in-memory store.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns the canonical credential-file path: either
    /// `$GOS_CREDENTIALS_FILE`, `$HOME/.gossamer/credentials.toml`,
    /// or `Err(NoHome)` when neither is set.
    pub fn default_path() -> Result<PathBuf, CredentialStoreError> {
        if let Ok(env_path) = std::env::var("GOS_CREDENTIALS_FILE") {
            return Ok(PathBuf::from(env_path));
        }
        let home = std::env::var("HOME").map_err(|_| CredentialStoreError::NoHome)?;
        Ok(PathBuf::from(home)
            .join(".gossamer")
            .join("credentials.toml"))
    }

    /// Loads the store from `path`. Returns an empty store when the
    /// file does not exist.
    pub fn load(path: &Path) -> Result<Self, CredentialStoreError> {
        match fs::read_to_string(path) {
            Ok(text) => Self::parse(&text).map_err(CredentialStoreError::Malformed),
            Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(Self::new()),
            Err(err) => Err(CredentialStoreError::Io(err.to_string())),
        }
    }

    /// Loads the store from the canonical path.
    pub fn load_default() -> Result<Self, CredentialStoreError> {
        let path = Self::default_path()?;
        Self::load(&path)
    }

    /// Returns the credential for `registry_url`, if any.
    #[must_use]
    pub fn get(&self, registry_url: &str) -> Option<&Credential> {
        self.entries.get(registry_url)
    }

    /// Stores `credential` under `registry_url`.
    pub fn insert(&mut self, registry_url: impl Into<String>, credential: Credential) {
        self.entries.insert(registry_url.into(), credential);
    }

    /// Removes the entry for `registry_url`, returning whether one
    /// was present.
    pub fn remove(&mut self, registry_url: &str) -> bool {
        self.entries.remove(registry_url).is_some()
    }

    /// Writes the store to `path` atomically (write-to-tmp + rename),
    /// restricted to the current user: mode 600 on POSIX, an owner-only DACL
    /// on Windows. The restriction is applied to the temp file before the
    /// rename so the credential bytes are never visible to other users; a
    /// failure to restrict aborts the write rather than leaving an
    /// world-readable file in place.
    pub fn save(&self, path: &Path) -> Result<(), CredentialStoreError> {
        write_private_file(path, self.render().as_bytes())
            .map_err(|e| CredentialStoreError::Io(e.to_string()))
    }

    /// Writes the store to the canonical path.
    pub fn save_default(&self) -> Result<(), CredentialStoreError> {
        let path = Self::default_path()?;
        self.save(&path)
    }

    /// Renders the store to canonical TOML.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# gossamer credentials store v1\n");
        out.push_str("# Generated by `gos login`. Do not commit.\n\n");
        for (url, cred) in &self.entries {
            out.push_str(&format!("[registries.{}]\n", quote(url)));
            out.push_str(&format!("token = {}\n\n", quote(&cred.token)));
        }
        out
    }

    /// Parses a credential file previously produced by [`Self::render`].
    pub fn parse(text: &str) -> Result<Self, String> {
        let mut entries: BTreeMap<String, Credential> = BTreeMap::new();
        let mut current_url: Option<String> = None;
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(inner) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                if let Some(after) = inner.trim().strip_prefix("registries.") {
                    let url = unquote(after.trim());
                    current_url = Some(url);
                } else {
                    return Err(format!("unknown section [{inner}]"));
                }
                continue;
            }
            let (key, value) = line
                .split_once('=')
                .ok_or_else(|| format!("malformed credential line: {line}"))?;
            let key = key.trim();
            let value = unquote(value.trim());
            let url = current_url
                .clone()
                .ok_or_else(|| format!("entry {key} outside of [registries.…]"))?;
            if key == "token" {
                entries.insert(url, Credential { token: value });
            }
        }
        Ok(Self { entries })
    }
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        if c == '\\' || c == '"' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

fn unquote(s: &str) -> String {
    let trimmed = s.trim();
    let Some(inner) = trimmed.strip_prefix('"').and_then(|x| x.strip_suffix('"')) else {
        return trimmed.to_string();
    };
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c == '\\'
            && let Some(next) = chars.next()
        {
            out.push(next);
        } else {
            out.push(c);
        }
    }
    out
}

/// Writes `bytes` to `path` atomically, readable by the current user only.
///
/// The temporary file is owner-only from the moment it exists - mode 600 on
/// POSIX, an owner-only DACL on Windows - so the secret is never visible to
/// another user, and a rename puts it in place whole.
pub(crate) fn write_private_file(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_file_name(format!(
        ".{}.tmp-{}-{}",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("private"),
        std::process::id(),
        CREDENTIAL_WRITE_ID.fetch_add(1, Ordering::Relaxed),
    ));
    let result = (|| {
        let mut options = fs::OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&tmp)?;
        #[cfg(windows)]
        restrict_to_owner(&tmp)?;
        file.write_all(bytes)?;
        file.sync_all()
    })();
    if let Err(err) = result {
        let _ = fs::remove_file(&tmp);
        return Err(err);
    }
    if let Err(err) = fs::rename(&tmp, path) {
        let _ = fs::remove_file(&tmp);
        return Err(err);
    }
    Ok(())
}

/// Replaces a file's DACL with a single ACE granting the current user
/// read+write and nothing else, marking the DACL protected so inherited ACEs
/// are dropped. The Windows analogue of `chmod 0600`.
// Win32 ACL programming is inherently `unsafe` FFI; the block is
// self-contained and audited (two-call TOKEN_USER pattern + DACL set).
#[cfg(windows)]
#[allow(unsafe_code, reason = "Windows ACL editing has no safe wrapper in std")]
fn restrict_to_owner(path: &Path) -> std::io::Result<()> {
    use std::io;
    use std::os::windows::ffi::OsStrExt;

    use windows_sys::Win32::Foundation::{CloseHandle, ERROR_SUCCESS, HANDLE, LocalFree};
    use windows_sys::Win32::Security::Authorization::{
        EXPLICIT_ACCESS_W, SE_FILE_OBJECT, SET_ACCESS, SetEntriesInAclW, SetNamedSecurityInfoW,
        TRUSTEE_IS_SID, TRUSTEE_IS_USER, TRUSTEE_W,
    };
    use windows_sys::Win32::Security::{
        ACL, DACL_SECURITY_INFORMATION, GetTokenInformation, NO_INHERITANCE,
        PROTECTED_DACL_SECURITY_INFORMATION, TOKEN_QUERY, TOKEN_USER, TokenUser,
    };
    use windows_sys::Win32::Storage::FileSystem::{FILE_GENERIC_READ, FILE_GENERIC_WRITE};
    use windows_sys::Win32::System::Threading::{GetCurrentProcess, OpenProcessToken};

    // SAFETY: every pointer the Win32 calls below receive is a local, a buffer this function owns
    // and sizes as the call reports, or the SID inside that buffer; each handle and ACL they
    // answer is released on every path.
    unsafe {
        let mut token: HANDLE = std::ptr::null_mut();
        if OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &raw mut token) == 0 {
            return Err(io::Error::last_os_error());
        }
        // Two-call pattern: size the buffer, then read TOKEN_USER.
        let mut len: u32 = 0;
        GetTokenInformation(token, TokenUser, std::ptr::null_mut(), 0, &raw mut len);
        // Word-sized storage gives `TOKEN_USER` the 8-byte alignment it needs.
        let mut buf = vec![0u64; (len as usize).div_ceil(8)];
        if GetTokenInformation(token, TokenUser, buf.as_mut_ptr().cast(), len, &raw mut len) == 0 {
            CloseHandle(token);
            return Err(io::Error::last_os_error());
        }
        let token_user = &*buf.as_ptr().cast::<TOKEN_USER>();
        let sid = token_user.User.Sid;

        let mut ea: EXPLICIT_ACCESS_W = std::mem::zeroed();
        ea.grfAccessPermissions = FILE_GENERIC_READ | FILE_GENERIC_WRITE;
        ea.grfAccessMode = SET_ACCESS;
        ea.grfInheritance = NO_INHERITANCE;
        ea.Trustee = TRUSTEE_W {
            pMultipleTrustee: std::ptr::null_mut(),
            MultipleTrusteeOperation: 0,
            TrusteeForm: TRUSTEE_IS_SID,
            TrusteeType: TRUSTEE_IS_USER,
            ptstrName: sid.cast(),
        };

        let mut acl: *mut ACL = std::ptr::null_mut();
        let rc = SetEntriesInAclW(1, &raw const ea, std::ptr::null_mut(), &raw mut acl);
        CloseHandle(token);
        if rc != ERROR_SUCCESS {
            return Err(io::Error::from_raw_os_error(rc as i32));
        }

        let wide: Vec<u16> = path
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect();
        let rc = SetNamedSecurityInfoW(
            wide.as_ptr().cast_mut(),
            SE_FILE_OBJECT,
            DACL_SECURITY_INFORMATION | PROTECTED_DACL_SECURITY_INFORMATION,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
            acl,
            std::ptr::null_mut(),
        );
        if !acl.is_null() {
            LocalFree(acl.cast());
        }
        if rc != ERROR_SUCCESS {
            return Err(io::Error::from_raw_os_error(rc as i32));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn store_round_trips_through_text() {
        let mut store = CredentialStore::new();
        store.insert(
            "https://pkg.gossamer.dev",
            Credential {
                token: "abc.def.ghi".to_string(),
            },
        );
        let rendered = store.render();
        let back = CredentialStore::parse(&rendered).unwrap();
        assert_eq!(
            back.get("https://pkg.gossamer.dev").unwrap().token,
            "abc.def.ghi"
        );
    }
}
