//! Build-time work for the runtime crate.
//!
//! 1. Emits a `tsan` cfg when the crate is being compiled under
//!    `ThreadSanitizer` (`-Zsanitizer=thread`), so `lib.rs` can fall back to
//!    the default system allocator there. `mimalloc` (the normal global
//!    allocator) is incompatible with `TSan`: its lazy global lock init races
//!    on first allocation, and an uninstrumented allocator blinds `TSan` to
//!    real heap races. `cfg(sanitize)` is nightly-only, so the flag is read
//!    from the rustflags the sanitizer job sets.
//! 2. Generates the name-to-address table for every `gos_rt_*` export
//!    (`src/symbols.rs` includes it). The table is derived from the
//!    definitions themselves, so a helper the runtime defines is reachable by
//!    name with no second list to keep in step.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rustc-check-cfg=cfg(tsan)");
    // `cargo-fuzz` sets `--cfg fuzzing`; declare it so the allocator
    // gates in `lib.rs` / `rc.rs` (which fall back to the system
    // allocator under the fuzz harness) don't trip `unexpected_cfgs`.
    println!("cargo:rustc-check-cfg=cfg(fuzzing)");
    println!("cargo:rerun-if-env-changed=RUSTFLAGS");
    println!("cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS");

    let flags = std::env::var("CARGO_ENCODED_RUSTFLAGS")
        .ok()
        .filter(|s| !s.is_empty())
        .or_else(|| std::env::var("RUSTFLAGS").ok())
        .unwrap_or_default();

    if flags.contains("sanitizer=thread") {
        println!("cargo:rustc-cfg=tsan");
    }

    generate_symbol_table();
}

/// One `gos_rt_*` export: the module that defines it and every `cfg` that
/// must hold for it to exist, the module chain's included.
struct Export {
    module: String,
    cfgs: Vec<String>,
}

fn generate_symbol_table() {
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    let src = manifest.join("src");
    let mut files = Vec::new();
    collect_sources(&src, &mut files);
    files.sort();

    let mut found: BTreeMap<String, Export> = BTreeMap::new();
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        let text = read(file);
        let exports = scan_exports(&text);
        if exports.is_empty() {
            continue;
        }
        let (module, module_cfgs) = module_of(&src, file);
        for (name, cfgs) in exports {
            let mut all = module_cfgs.clone();
            all.extend(cfgs);
            let previous = found.insert(
                name.clone(),
                Export {
                    module: module.clone(),
                    cfgs: all,
                },
            );
            assert!(
                previous.is_none(),
                "symbol table: `{name}` is exported twice (second in {})",
                file.display()
            );
        }
    }

    let mut out = String::from("// Generated by build.rs from the runtime's own definitions.\n\n");
    out.push_str("static GENERATED: &[SymbolEntry] = &[\n");
    for (name, export) in &found {
        for cfg in &export.cfgs {
            let _ = writeln!(out, "    {cfg}");
        }
        let _ = writeln!(
            out,
            "    SymbolEntry {{ name: \"{name}\", addr: SymbolAddr({}::{name} as *const ()) }},",
            export.module
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env("OUT_DIR")).join("symbol_table.rs");
    if let Err(err) = std::fs::write(&dest, out) {
        panic!("symbol table: writing {}: {err}", dest.display());
    }
}

fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|err| panic!("symbol table: {key}: {err}"))
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("symbol table: reading {}: {err}", path.display()))
}

fn collect_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("symbol table: listing {}: {err}", dir.display()));
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_sources(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// The Rust path of the module `file` defines, and the `cfg`s on every
/// `mod` declaration between it and the crate root.
///
/// `src/c_abi/fs.rs` is `crate::c_abi::fs`, declared in `src/c_abi.rs`;
/// `src/preempt.rs` is `crate::preempt`, declared in `src/lib.rs`. A file
/// whose declaration cannot be found (one reached through `#[path]`) stops
/// the build rather than producing an address the compiler cannot resolve.
fn module_of(src: &Path, file: &Path) -> (String, Vec<String>) {
    let rel = file
        .strip_prefix(src)
        .unwrap_or_else(|_| panic!("symbol table: {} is outside src", file.display()));
    let mut segments: Vec<String> = rel
        .components()
        .map(|c| {
            c.as_os_str()
                .to_string_lossy()
                .trim_end_matches(".rs")
                .to_string()
        })
        .collect();
    if segments.last().is_some_and(|last| last == "mod") {
        segments.pop();
    }
    if segments == ["lib"] {
        return ("crate".to_string(), Vec::new());
    }

    let mut cfgs = Vec::new();
    for depth in 0..segments.len() {
        let parent = &segments[..depth];
        let child = &segments[depth];
        let parent_file = if parent.is_empty() {
            src.join("lib.rs")
        } else {
            let base = parent.iter().fold(src.to_path_buf(), |p, s| p.join(s));
            let flat = base.with_extension("rs");
            if flat.is_file() {
                flat
            } else {
                base.join("mod.rs")
            }
        };
        let decl = module_declaration_cfgs(&read(&parent_file), child).unwrap_or_else(|| {
            panic!(
                "symbol table: no `mod {child};` in {} for {}",
                parent_file.display(),
                file.display()
            )
        });
        cfgs.extend(decl);
    }
    (format!("crate::{}", segments.join("::")), cfgs)
}

/// The `cfg` attributes on `mod name;` in `text`, or `None` when the file
/// declares no such module.
fn module_declaration_cfgs(text: &str, name: &str) -> Option<Vec<String>> {
    let mut attrs = Attributes::default();
    for line in text.lines() {
        let trimmed = line.trim();
        if attrs.absorb(trimmed) {
            continue;
        }
        let item = strip_visibility(trimmed);
        if item.strip_prefix("mod ").map(str::trim) == Some(&format!("{name};")) {
            return Some(attrs.take_cfgs());
        }
        attrs.clear();
    }
    None
}

fn strip_visibility(item: &str) -> &str {
    for prefix in ["pub(crate) ", "pub(super) ", "pub "] {
        if let Some(rest) = item.strip_prefix(prefix) {
            return rest;
        }
    }
    item
}

/// The outer attributes read so far above the next item, with multi-line
/// attributes joined into one string.
#[derive(Default)]
struct Attributes {
    done: Vec<String>,
    open: Option<(String, i32)>,
}

impl Attributes {
    /// Takes `line` when it is part of an attribute, a comment, or blank, and
    /// answers whether it did.
    fn absorb(&mut self, line: &str) -> bool {
        if let Some((mut text, depth)) = self.open.take() {
            text.push(' ');
            text.push_str(line);
            let depth = depth + bracket_balance(line);
            if depth > 0 {
                self.open = Some((text, depth));
            } else {
                self.done.push(text);
            }
            return true;
        }
        if line.starts_with("#[") {
            let depth = bracket_balance(line);
            if depth > 0 {
                self.open = Some((line.to_string(), depth));
            } else {
                self.done.push(line.to_string());
            }
            return true;
        }
        line.is_empty() || line.starts_with("//")
    }

    fn cfgs(&self) -> Vec<String> {
        self.done
            .iter()
            .filter(|attr| attr.starts_with("#[cfg("))
            .cloned()
            .collect()
    }

    fn take_cfgs(&mut self) -> Vec<String> {
        let cfgs = self.cfgs();
        self.clear();
        cfgs
    }

    fn clear(&mut self) {
        self.done.clear();
        self.open = None;
    }
}

/// Net `[` minus `]` on `line`, ignoring brackets inside string literals.
fn bracket_balance(line: &str) -> i32 {
    let mut depth = 0;
    let mut in_string = false;
    let mut escaped = false;
    for c in line.chars() {
        if in_string {
            match c {
                _ if escaped => escaped = false,
                '\\' => escaped = true,
                '"' => in_string = false,
                _ => {}
            }
            continue;
        }
        match c {
            '"' => in_string = true,
            '[' => depth += 1,
            ']' => depth -= 1,
            _ => {}
        }
    }
    depth
}

/// Every `gos_rt_*` export `text` defines, with the `cfg`s guarding it.
///
/// An export is a `pub (unsafe)? extern "C"` (or `"C-unwind"`) function at
/// item level, or a symbol an export-generating macro invocation names: the
/// first argument of a one-line `macro!(gos_rt_name, ..)`, or an argument
/// line `gos_rt_name,` / `gos_rt_name = (..),` of a multi-line invocation.
fn scan_exports(text: &str) -> Vec<(String, Vec<String>)> {
    let mut out = Vec::new();
    let mut attrs = Attributes::default();
    let mut invocation_cfgs: Option<Vec<String>> = None;
    for line in text.lines() {
        let trimmed = line.trim_start();
        let at_item_level = !line.starts_with(char::is_whitespace);
        if at_item_level && invocation_cfgs.is_some() && !trimmed.is_empty() {
            invocation_cfgs = None;
            if trimmed.starts_with(')') || trimmed.starts_with('}') {
                continue;
            }
        }
        if at_item_level && attrs.absorb(trimmed) {
            continue;
        }
        if let Some(name) = extern_fn_name(trimmed).filter(|_| at_item_level) {
            out.push((name, attrs.take_cfgs()));
            continue;
        }
        if let Some(name) = one_line_macro_export(trimmed) {
            out.push((name, attrs.take_cfgs()));
            continue;
        }
        if let Some(cfgs) = &invocation_cfgs {
            if let Some(name) = multi_line_macro_arg_export(trimmed) {
                out.push((name, cfgs.clone()));
            }
            continue;
        }
        if at_item_level {
            if opens_macro_invocation(trimmed) {
                invocation_cfgs = Some(attrs.take_cfgs());
            } else {
                attrs.clear();
            }
        }
    }
    out
}

fn extern_fn_name(line: &str) -> Option<String> {
    let rest = [
        "pub unsafe extern \"C\" fn ",
        "pub extern \"C\" fn ",
        "pub unsafe extern \"C-unwind\" fn ",
        "pub extern \"C-unwind\" fn ",
    ]
    .iter()
    .find_map(|prefix| line.strip_prefix(prefix))?;
    let name: String = rest.chars().take_while(|&c| is_ident_char(c)).collect();
    name.starts_with("gos_rt_").then_some(name)
}

/// `some_macro!(gos_rt_name, ..)` names the export `gos_rt_name`. The
/// identifier must be a whole argument, so a runtime call passed as an
/// argument (`bar!(gos_rt_x(0, y))`) is not mistaken for one.
fn one_line_macro_export(line: &str) -> Option<String> {
    let bang = line.find("!(")?;
    let macro_name = &line[..bang];
    if macro_name.is_empty() || !macro_name.chars().all(is_ident_char) {
        return None;
    }
    let after = line[bang + 2..].trim_start();
    let token: String = after.chars().take_while(|&c| is_ident_char(c)).collect();
    if !token.starts_with("gos_rt_") {
        return None;
    }
    let next = after[token.len()..].trim_start().chars().next();
    matches!(next, Some(',' | ')')).then_some(token)
}

/// An argument line of a multi-line invocation that is a `gos_rt_*`
/// identifier on its own, written `gos_rt_name,` or `gos_rt_name = (..),`.
fn multi_line_macro_arg_export(line: &str) -> Option<String> {
    let token: String = line.chars().take_while(|&c| is_ident_char(c)).collect();
    if !token.starts_with("gos_rt_") {
        return None;
    }
    let rest = line[token.len()..].trim_start();
    if rest == "," {
        return Some(token);
    }
    let named = rest.strip_prefix('=')?.trim_start();
    (named.starts_with('(') && named.ends_with("),")).then_some(token)
}

/// An item-level `name!(` or `name! {` whose arguments continue on the
/// following lines.
fn opens_macro_invocation(line: &str) -> bool {
    let Some(bang) = line.find('!') else {
        return false;
    };
    let name = &line[..bang];
    if name.is_empty() || !name.chars().all(is_ident_char) || name == "macro_rules" {
        return false;
    }
    matches!(line[bang + 1..].trim(), "(" | "{" | "[")
}

fn is_ident_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}
