#![allow(
    unused_imports,
    dead_code,
    unreachable_pub,
    missing_docs,
    clippy::wildcard_imports,
    clippy::too_many_lines,
    clippy::too_many_arguments,
    clippy::similar_names,
    clippy::many_single_char_names,
    clippy::items_after_statements,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::doc_markdown,
    clippy::option_if_let_else,
    clippy::match_same_arms,
    clippy::if_not_else,
    clippy::single_match_else,
    clippy::needless_pass_by_value,
    clippy::manual_let_else,
    clippy::redundant_else,
    clippy::collapsible_if,
    clippy::collapsible_else_if,
    clippy::map_unwrap_or,
    clippy::struct_excessive_bools,
    clippy::module_name_repetitions,
    clippy::unnecessary_wraps,
    clippy::large_enum_variant,
    clippy::if_same_then_else,
    clippy::single_match,
    clippy::useless_conversion,
    clippy::needless_borrows_for_generic_args,
    clippy::let_and_return,
    clippy::needless_collect,
    clippy::elidable_lifetime_names,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::must_use_candidate,
    clippy::missing_const_for_fn,
    clippy::needless_range_loop,
    clippy::ptr_arg,
    clippy::ptr_as_ptr,
    clippy::redundant_closure,
    clippy::redundant_closure_for_method_calls,
    clippy::semicolon_if_nothing_returned,
    clippy::single_call_fn,
    clippy::unused_self,
    clippy::range_plus_one,
    clippy::missing_safety_doc,
    clippy::not_unsafe_ptr_arg_deref,
    clippy::cast_ptr_alignment,
    clippy::manual_assert,
    clippy::manual_string_new,
    clippy::match_bool,
    clippy::nonminimal_bool,
    clippy::redundant_pattern_matching,
    clippy::useless_let_if_seq
)]
//! Static manifest of every registered stdlib module.
//! Each stdlib milestone extends this table with
//! the modules it adds. Entries are listed in phase-introduction order
//! so a `gos doc` walk renders modules in the same sequence as the
//! implementation plan.

#![forbid(unsafe_code)]
use crate::registry::{StdItem, StdItemKind, StdModule};

use super::*;

/// Single source of truth for the stdlib's public surface.
pub const ALL_MODULES: &[StdModule] = &[
    FMT,
    IO,
    OS,
    OS_EXEC,
    OS_SIGNAL,
    ENV,
    PROCESS,
    THREAD,
    STRINGS,
    STRCONV,
    COLLECTIONS,
    NET,
    HTTP,
    ENCODING_JSON,
    SYNC,
    TIME,
    PANIC,
    // Stream D additions (QOL_PLAN.md).
    ERRORS,
    FLAG,
    PATH,
    FS,
    BYTES,
    BUFIO,
    NET_URL,
    SLOG,
    ENCODING_BASE64,
    ENCODING_HEX,
    ENCODING_BINARY,
    CONTEXT,
    CRYPTO_RAND,
    CRYPTO_SHA256,
    CRYPTO_HMAC,
    CRYPTO_SUBTLE,
    UTF8,
    MATH_RAND,
    TESTING,
    HTTPTEST,
    IMAGE,
    RUNTIME,
    TLS,
    REGEX,
    COMPRESS_GZIP,
    // Track B additions: crypto breadth, encoding, templates, db.
    CRYPTO_SHA512,
    CRYPTO_BLAKE3,
    CRYPTO_AEAD,
    CRYPTO_ED25519,
    CRYPTO_ECDSA,
    CRYPTO_X509,
    CRYPTO_KDF,
    ENCODING_YAML,
    HTML_TEMPLATE,
    HTML,
    DATABASE_SQL,
    // P0 gap-fill: math, unicode, utf8 expansion, encoding, strings.
    MATH,
    MATH_BITS,
    UNICODE,
    ENCODING_CSV,
    ENCODING_PEM,
    // P0 gap-fill: utf16, iter.
    UTF16,
    ITER,
    OPTION,
    RESULT,
    // 0.4.0 - HTTP/2 folded into HTTP per the Go model;
    // extended HTTP surface, archives, big-int, FNV, XML, base32 /
    // ascii85, insecure crypto, cipher modes.
    HTTP_ROUTER,
    HTTP_MIDDLEWARE,
    HTTP_STATIC_FILES,
    HTTP_PROXY,
    HTTP_WEBSOCKET,
    HTTP_SSE,
    HTTP_CHUNKED,
    HTTP_NATIVE_CLIENT,
    ARCHIVE_ZIP,
    ARCHIVE_TAR,
    COMPRESS_FLATE,
    COMPRESS_ZLIB,
    COMPRESS_BZIP2,
    ENCODING_XML,
    ENCODING_BASE32,
    ENCODING_ASCII85,
    HASH_FNV,
    HASH_CRC32,
    HASH_CRC32C,
    HASH_ADLER32,
    MATH_BIG,
    CRYPTO_INSECURE,
    // 0.7.0 stdlib expansion - uuid, container module, mime, toml,
    // httptest, netip, os::user, plus auto-derive extensions.
    UUID,
    OS_USER,
    NETIP,
    NET_IP,
    SMTP,
    MIME,
    ENCODING_TOML,
    SORT,
    // 0.8.0 - HTTP server stack (cookie / csrf / form / health /
    // multipart / query / session / state), JWT, lifecycle,
    // validate, argon2id password facade.
    HTTP_COOKIE,
    HTTP_CSRF,
    HTTP_FORM,
    HTTP_HEALTH,
    HTTP_MULTIPART,
    HTTP_QUERY,
    HTTP_SESSION,
    HTTP_STATE,
    JWT,
    LIFECYCLE,
    VALIDATE,
    CRYPTO_PASSWORD,
    // 0.9.0 - observability (metrics, distributed tracing), HTTP/3,
    // Zstandard.
    METRICS,
    PPROF,
    TRACE,
    HTTP_H3,
    COMPRESS_ZSTD,
];
